# Generated by Django 6.0.6 on 2026-06-20 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', max_length=20, verbose_name='Plan')),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='trial', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name="Date d'expiration")),
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.garage', verbose_name='Garage')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], max_length=20, verbose_name='Méthode')),
                ('paid_at', models.DateField(verbose_name='Date de paiement')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': 'Paiement abonnement',
                'verbose_name_plural': 'Paiements abonnements',
                'ordering': ['-paid_at'],
            },
        ),
    ]
