# Generated by Django 6.0.6 on 2026-06-20 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_garage_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('category', models.CharField(choices=[('location', 'Loyer / Location'), ('nourriture', 'Nourriture'), ('consommables', 'Consommables garage'), ('salaires', 'Salaires'), ('impots', 'Impôts / Taxes'), ('autres', 'Autres')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], default='cash', max_length=20)),
                ('employee', models.ForeignKey(blank=True, help_text='Renseigner uniquement pour les salaires.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_expenses', to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
