# Generated by Django 6.0.6 on 2026-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom du garage')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, verbose_name='Numéro WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('faest_supplier_enabled', models.BooleanField(default=False, help_text='Permet à ce garage de commander des pièces directement via FAEST depuis la plateforme.', verbose_name='Approvisionnement FAEST activé')),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
                'ordering': ['name'],
            },
        ),
    ]
