# Generated by Django 6.0.6 on 2026-06-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo affiché dans l'interface du garage.", null=True, upload_to='garages/logos/', verbose_name='Logo'),
        ),
    ]
