# Generated by Django 6.0.6 on 2026-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_garage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='cachet',
            field=models.ImageField(blank=True, help_text='Image du cachet ou tampon officiel.', null=True, upload_to='garages/cachets/', verbose_name='Cachet / Tampon'),
        ),
        migrations.AddField(
            model_name='garage',
            name='ifu',
            field=models.CharField(blank=True, help_text='Identifiant Fiscal Unique', max_length=50, verbose_name='IFU'),
        ),
        migrations.AddField(
            model_name='garage',
            name='rccm',
            field=models.CharField(blank=True, help_text='Registre du Commerce et du Crédit Mobilier', max_length=50, verbose_name='RCCM'),
        ),
        migrations.AddField(
            model_name='garage',
            name='signature',
            field=models.ImageField(blank=True, help_text='Image de la signature (PNG transparent recommandé).', null=True, upload_to='garages/signatures/', verbose_name='Signature'),
        ),
    ]
