# Generated by Django 6.0.6 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_ifu_rccm_signature_cachet'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='key_board_size',
            field=models.PositiveIntegerField(default=40, help_text='Nombre de crochets/emplacements numérotés sur le tableau à clés du garage.', verbose_name='Emplacements du tableau à clés'),
        ),
    ]
