# Generated by Django 5.2.17 on 2026-08-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_garage_key_board_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
