# Generated by Django 6.0.6 on 2026-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_garage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
