# Generated by Django 6.0.6 on 2026-09-04 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_garage_feature_overrides'),
        ('workshops', '0002_create_default_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopsection',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage'),
        ),
    ]
