# Generated by Django 6.0.6 on 2026-06-23 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('tenants', '0002_garage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage'),
        ),
    ]
