# Generated by Django 6.0.6 on 2026-06-17 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_type', models.CharField(choices=[('individual', 'Particulier'), ('company', 'Entreprise')], default='individual', max_length=20)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom / Raison sociale')),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=30, verbose_name='Immatriculation')),
                ('make', models.CharField(max_length=60, verbose_name='Marque')),
                ('model', models.CharField(max_length=60, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], default='petrol', max_length=20)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='Numéro de châssis (VIN)')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage actuel')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.client')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage')),
            ],
            options={
                'ordering': ['plate_number'],
                'constraints': [models.UniqueConstraint(fields=('garage', 'plate_number'), name='unique_plate_per_garage')],
            },
        ),
    ]
