# Generated by Django 6.0.6 on 2026-07-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0003_ifu_rccm_signature_cachet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='arrival_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name="N° d'arrivée"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_in_garage',
            field=models.BooleanField(default=True, verbose_name='Actuellement au garage'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='key_tag',
            field=models.CharField(blank=True, help_text='Étiquette physique de la clé, ex: A-12', max_length=50, verbose_name='Repère de clé'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='stored_since',
            field=models.DateField(blank=True, null=True, verbose_name='Depuis le'),
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Légende')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clients.vehicle')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
