# Generated by Django 6.0.6 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_vehicle_arrival_keytag_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='key_token',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text="Numéro attribué automatiquement, imprimé sur l'étiquette et affecté à un emplacement du tableau à clés.", null=True, verbose_name='N° tableau à clés'),
        ),
    ]
