# Generated by Django 6.0.6 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0003_vehicle_key_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='catalog.vehiclemake', verbose_name='Marque (catalogue)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='catalog.vehiclemodel', verbose_name='Modèle (catalogue)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, help_text='Renseigné automatiquement si une marque du catalogue est choisie.', max_length=60, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Renseigné automatiquement si un modèle du catalogue est choisi.', max_length=60, verbose_name='Modèle'),
        ),
    ]
