# Generated by Django 6.0.6 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0002_part_catalog_part_alter_part_id_and_more'),
        ('tenants', '0004_garage_key_board_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement pour les comptes fournisseurs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garage',
            field=models.ForeignKey(blank=True, help_text='Vide pour le staff plateforme (superuser) et les comptes fournisseurs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.garage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur garage'), ('reception', 'Réceptionniste'), ('mechanic', 'Mécanicien'), ('cashier', 'Caissier'), ('storekeeper', 'Magasinier'), ('supplier', 'Fournisseur')], max_length=20),
        ),
    ]
