# Generated by Django 6.0.6 on 2026-07-27 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_visits', '0001_initial'),
        ('tenants', '0003_ifu_rccm_signature_cachet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalvisit',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage'),
        ),
    ]
