# Generated by Django 6.0.6 on 2026-09-04 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('tenants', '0007_garage_feature_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='original_file',
            field=models.FileField(blank=True, help_text="PDF ou image provenant de l'outil de diagnostic.", null=True, upload_to='diagnostics/%Y/%m/', verbose_name='Fichier scanner original'),
        ),
    ]
