# Generated by Django 6.0.6 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenants', '0004_garage_key_board_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='catalog_part',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, la pièce est liée au catalogue de référence partagé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_stocks', to='catalog.catalogpart', verbose_name='Pièce catalogue'),
        ),
        migrations.CreateModel(
            name='SupplierPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix fournisseur (FCFA)')),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='Stock disponible chez le fournisseur')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai livraison (jours)')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='Réf. interne fournisseur')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('catalog_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.catalogpart')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_offers', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Offre fournisseur',
                'verbose_name_plural': 'Offres fournisseurs',
                'ordering': ['catalog_part__name', 'unit_price'],
                'constraints': [models.UniqueConstraint(fields=('garage', 'supplier', 'catalog_part'), name='unique_supplier_part_per_garage')],
            },
        ),
    ]
