# Generated by Django 6.0.6 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_part_catalog_part_alter_part_id_and_more'),
        ('tenants', '0004_garage_key_board_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Entrée / Réapprovisionnement'), ('out', 'Sortie / Vente'), ('adjust', "Ajustement d'inventaire")], max_length=10)),
                ('quantity', models.IntegerField(help_text='Positif pour entrée, positif aussi pour sortie (le signe est déduit du type).')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente réel (peut différer du prix catalogue).', max_digits=12, null=True, verbose_name='Prix appliqué (FCFA)')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('destination_garage', models.ForeignKey(blank=True, help_text='Renseigné pour une sortie vendue à un garage identifié.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_purchases', to='tenants.garage', verbose_name='Garage destinataire')),
                ('supplier_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.supplierpart', verbose_name='Offre fournisseur')),
            ],
            options={
                'verbose_name': 'Mouvement stock fournisseur',
                'verbose_name_plural': 'Mouvements stock fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
