# Generated by Django 6.0.6 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_part_id_alter_stockmovement_id_and_more'),
        ('tenants', '0004_garage_key_board_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le taux plateforme par défaut.', max_digits=5, null=True, verbose_name='Taux de commission plateforme (%)'),
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise au fournisseur'), ('validated', 'Validée par le fournisseur'), ('rejected', 'Rejetée par le fournisseur'), ('shipped', 'Expédiée'), ('delivered', 'Livrée / Réceptionnée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total (FCFA)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux commission (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Commission plateforme (FCFA)')),
                ('garage_note', models.TextField(blank=True, verbose_name='Note du garage')),
                ('supplier_note', models.TextField(blank=True, verbose_name='Note du fournisseur')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, verbose_name='Motif de rejet')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='tenants.garage')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_received', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_reference', models.CharField(blank=True, max_length=100)),
                ('catalog_name', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.supplierorder')),
                ('supplier_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='inventory.supplierpart')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
