# Generated by Django 6.0.6 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_commission_rate_alter_part_id_and_more'),
    ]

    operations = [
        # On ajoute d'abord le champ en nullable pour permettre le backfill
        # des lignes existantes, puis on le passe en NOT NULL avec valeur par
        # défaut '' pour respecter la contrainte cote application.
        migrations.AddField(
            model_name='supplierpart',
            name='g_code',
            field=models.CharField(
                verbose_name='G-CODE (code de compatibilité)',
                max_length=80,
                db_index=True,
                default='',
                help_text="Code officiel de la pièce (OEM/fabricant) garantissant sa compatibilité avec le véhicule.",
            ),
            preserve_default=False,
        ),
    ]
