# Generated by Django 6.0.6 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplierpart_g_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderline',
            name='g_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='G-CODE'),
        ),
    ]
