# Generated by Django 6.0.6 on 2026-09-02 09:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplierorderline_g_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Personne à contacter'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ifu',
            field=models.CharField(blank=True, max_length=50, verbose_name='IFU'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rccm',
            field=models.CharField(blank=True, max_length=50, verbose_name='RCCM'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='supplierpart',
            name='alert_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Une alerte apparaît sur la plateforme lorsque le stock atteint ce seuil.', verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='supplierstockmovement',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Client / Acheteur'),
        ),
        migrations.AddField(
            model_name='supplierstockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('credit', 'À crédit')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='supplierstockmovement',
            name='sale_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence de vente'),
        ),
        migrations.AddField(
            model_name='supplierstockmovement',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.supplierorder', verbose_name="Commande d'origine"),
        ),
        migrations.CreateModel(
            name='SupplierExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('purchase', 'Achat de marchandises'), ('transport', 'Transport / Livraison'), ('salary', 'Salaires'), ('rent', 'Loyer'), ('utilities', 'Eau / Électricité / Internet'), ('tax', 'Taxes et impôts'), ('maintenance', 'Entretien / Réparation'), ('marketing', 'Communication / Marketing'), ('other', 'Autre')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('credit', 'À crédit')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('receipt', models.FileField(blank=True, upload_to='suppliers/expenses/%Y/%m/', verbose_name='Justificatif')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Dépense fournisseur',
                'verbose_name_plural': 'Dépenses fournisseurs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
