# Generated by Django 6.0.6 on 2026-06-30 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('tenants', '0002_garage_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_name', models.CharField(blank=True, help_text="Remplir uniquement si le client n'est pas dans la base.", max_length=150, verbose_name='Nom client (libre)')),
                ('status', models.CharField(choices=[('proforma', 'Facture Proforma'), ('invoice', 'Facture Définitive'), ('receipt', 'Reçu (Payée)')], default='proforma', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoices', to='clients.client')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.garage')),
            ],
            options={
                'verbose_name': 'Facture Proforma',
                'verbose_name_plural': 'Factures Proforma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unit. (FCFA)')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_lines', to='inventory.part')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.proformainvoice')),
            ],
        ),
    ]
