# Generated by Django 6.0.6 on 2026-07-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplog',
            name='direction',
            field=models.CharField(choices=[('out', 'Sortant'), ('in', 'Entrant')], default='out', max_length=3),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='wa_message_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID message WA'),
        ),
    ]
