# Generated by Django 6.0.6 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Catégorie')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Catégorie de pièce',
                'verbose_name_plural': 'Catégories de pièces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Marque')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='catalog/makes/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Marque de véhicule',
                'verbose_name_plural': 'Marques de véhicules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Modèle')),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année début')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année fin')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.vehiclemake')),
            ],
            options={
                'verbose_name': 'Modèle de véhicule',
                'verbose_name_plural': 'Modèles de véhicules',
                'ordering': ['make__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Référence unique (OEM, EAN ou code interne).', max_length=100, unique=True, verbose_name='Référence catalogue')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/parts/')),
                ('is_universal', models.BooleanField(default=False, help_text='Cocher si compatible avec tous les modèles (ex: huile, ampoule H4).', verbose_name='Universelle')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='catalog.partcategory')),
                ('compatible_models', models.ManyToManyField(blank=True, help_text='Modèles de véhicules pour lesquels cette pièce est adaptée.', related_name='compatible_parts', to='catalog.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Pièce de référence',
                'verbose_name_plural': 'Pièces de référence (catalogue)',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'slug'), name='unique_model_slug_per_make'),
        ),
    ]
